/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-13-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-13-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
Public Class AccCreation{
Public Static void CreateAccount(String x, String y){
List<Account> a = new List<Account>();
for(Account acc:a){
acc.Name=x ;
acc.Phone=y;
}
insert a;
}
}